<a href="https://colab.research.google.com/github/galaceangela/Convert-pandas-DataFrames-to-NumPy-arrays-or-dictionaries/blob/main/Convert%20pandas%20DataFrames%20to%20NumPy%20arrays%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/galaceangela/Convert-pandas-DataFrames-to-NumPy-arrays-or-dictionaries/main/linear.csv')

In [9]:
df.head()

            x           y
0    0.000000  -51.000000
1   25.000000  -12.000000
2  117.583220  134.907414
3  108.922466  134.085180
4   69.887445         NaN

In [10]:
df.to_numpy()

array([[  0.        , -51.        ],
       [ 25.        , -12.        ],
       [117.5832198 , 134.9074137 ],
       [108.9224662 , 134.0851795 ],
       [ 69.88744536,          nan],
       [ 96.83998269, 114.5306376 ],
       [ 51.77594025,  31.37643731],
       [ 35.01673734,   8.76463417],
       [ 79.45764646,  73.28534128],
       [ 45.3449093 ,  18.85986466],
       [ 77.76713229,  72.9466086 ],
       [ 55.85663802,  28.63728633],
       [ 51.8290553 ,  27.18413784],
       [ 36.07902502,  15.46895475],
       [ 80.63255196,  77.25552457],
       [124.4126644 , 147.817536  ],
       [ 38.88238694,  29.62914801],
       [ 85.24501874,  92.31571653],
       [105.4849878 , 111.063745  ],
       [ 36.82741469,   2.79748519],
       [ 98.61682009,  98.22796195],
       [102.1309415 , 117.0827211 ],
       [101.9740862 , 111.1555591 ],
       [122.5816416 , 147.0235042 ],
       [ 96.36839009,  99.62870641],
       [ 64.89044698,  47.94620302],
       [ 81.87156504,  80.51588907],
       [ 83.46634106,  76.65159462],
       [129.9988213 , 155.5832066 ],
       [129.5934245 , 155.830527  ],
       [ 71.30088195,  52.64410294],
       [ 89.63463319, 100.3291952 ],
       [ 82.74502445,  67.03050817],
       [ 84.29777124,  80.8896434 ],
       [ 93.6549342 ,  96.20409384],
       [ 37.33160529,  -6.2362947 ],
       [ 52.16604202,  23.5571594 ],
       [104.833943  , 107.7810191 ],
       [106.4639932 , 112.883657  ],
       [ 79.51558318,  72.00317212],
       [ 41.4999434 ,  20.25934009],
       [113.6214443 , 131.04384   ],
       [ 90.20451127,  94.77986788],
       [ 52.56692661,  28.21059566],
       [ 40.50463433,  14.17040121],
       [ 43.45292157,  23.19979105],
       [122.1252001 , 147.1272496 ],
       [ 55.16828222,  46.89089049],
       [ 96.44691123, 105.7562824 ],
       [119.2731974 , 126.4660848 ],
       [ 52.19022426,  42.06951797],
       [114.8983489 , 138.6278072 ],
       [126.0412086 , 139.406306  ],
       [ 93.14307012,          nan],
       [131.1618641 , 163.3539583 ],
       [ 55.35872543,  38.22375858],
       [ 94.59612783, 105.0461097 ],
       [ 75.91878744,  68.54098922],
       [ 96.9481879 , 100.2372769 ],
       [ 40.11139299,  15.2017754 ],
       [ 95.54238786,          nan],
       [ 66.46740141,  60.2143421 ],
       [120.6995729 ,          nan],
       [104.2402942 , 113.9349495 ],
       [ 82.65762179,          nan],
       [105.5341749 ,          nan],
       [ 87.34855969,  85.16272742],
       [ 69.40200784,  53.37775696],
       [127.3248623 , 160.4954569 ],
       [ 64.43689333,  43.39435848],
       [ 66.26465895,  58.1736831 ],
       [ 90.30720045,  81.64306345],
       [ 89.4048535 ,  87.64350868],
       [114.4503884 , 135.3976986 ],
       [134.4322939 , 159.0736094 ],
       [131.7902232 , 161.3630997 ],
       [ 99.56304732,  91.64481237],
       [132.7401928 , 166.1645443 ],
       [ 70.99088679,  54.86400482],
       [ 87.9094701 ,  78.97916469],
       [123.5807212 , 141.1303998 ],
       [107.6435614 , 119.0882793 ],
       [116.3612443 , 136.2293706 ],
       [ 62.73766606,  35.03959082],
       [112.0489047 , 130.8072421 ],
       [119.861603  , 136.2239313 ],
       [ 59.14093284,  43.34977918],
       [ 95.30589341, 106.1847674 ],
       [103.0198215 , 121.2744298 ],
       [109.2183446 , 115.1818431 ],
       [117.360594  , 137.4299149 ],
       [ 39.5196786 ,  16.02640021],
       [ 37.54642469,          nan],
       [129.9626909 , 141.0131341 ],
       [ 35.91420463,          nan],
       [ 43.85421968,  13.45049208],
       [ 72.88414185,  61.50699688],
       [120.7408594 , 133.9222973 ],
       [100.1797881 , 126.8271164 ],
       [ 59.33376537,  50.25779685],
       [120.1577567 , 144.7546765 ],
       [115.5391524 , 120.6973091 ]])

In [11]:
df.values

array([[  0.        , -51.        ],
       [ 25.        , -12.        ],
       [117.5832198 , 134.9074137 ],
       [108.9224662 , 134.0851795 ],
       [ 69.88744536,          nan],
       [ 96.83998269, 114.5306376 ],
       [ 51.77594025,  31.37643731],
       [ 35.01673734,   8.76463417],
       [ 79.45764646,  73.28534128],
       [ 45.3449093 ,  18.85986466],
       [ 77.76713229,  72.9466086 ],
       [ 55.85663802,  28.63728633],
       [ 51.8290553 ,  27.18413784],
       [ 36.07902502,  15.46895475],
       [ 80.63255196,  77.25552457],
       [124.4126644 , 147.817536  ],
       [ 38.88238694,  29.62914801],
       [ 85.24501874,  92.31571653],
       [105.4849878 , 111.063745  ],
       [ 36.82741469,   2.79748519],
       [ 98.61682009,  98.22796195],
       [102.1309415 , 117.0827211 ],
       [101.9740862 , 111.1555591 ],
       [122.5816416 , 147.0235042 ],
       [ 96.36839009,  99.62870641],
       [ 64.89044698,  47.94620302],
       [ 81.87156504,  80.51588907],
       [ 83.46634106,  76.65159462],
       [129.9988213 , 155.5832066 ],
       [129.5934245 , 155.830527  ],
       [ 71.30088195,  52.64410294],
       [ 89.63463319, 100.3291952 ],
       [ 82.74502445,  67.03050817],
       [ 84.29777124,  80.8896434 ],
       [ 93.6549342 ,  96.20409384],
       [ 37.33160529,  -6.2362947 ],
       [ 52.16604202,  23.5571594 ],
       [104.833943  , 107.7810191 ],
       [106.4639932 , 112.883657  ],
       [ 79.51558318,  72.00317212],
       [ 41.4999434 ,  20.25934009],
       [113.6214443 , 131.04384   ],
       [ 90.20451127,  94.77986788],
       [ 52.56692661,  28.21059566],
       [ 40.50463433,  14.17040121],
       [ 43.45292157,  23.19979105],
       [122.1252001 , 147.1272496 ],
       [ 55.16828222,  46.89089049],
       [ 96.44691123, 105.7562824 ],
       [119.2731974 , 126.4660848 ],
       [ 52.19022426,  42.06951797],
       [114.8983489 , 138.6278072 ],
       [126.0412086 , 139.406306  ],
       [ 93.14307012,          nan],
       [131.1618641 , 163.3539583 ],
       [ 55.35872543,  38.22375858],
       [ 94.59612783, 105.0461097 ],
       [ 75.91878744,  68.54098922],
       [ 96.9481879 , 100.2372769 ],
       [ 40.11139299,  15.2017754 ],
       [ 95.54238786,          nan],
       [ 66.46740141,  60.2143421 ],
       [120.6995729 ,          nan],
       [104.2402942 , 113.9349495 ],
       [ 82.65762179,          nan],
       [105.5341749 ,          nan],
       [ 87.34855969,  85.16272742],
       [ 69.40200784,  53.37775696],
       [127.3248623 , 160.4954569 ],
       [ 64.43689333,  43.39435848],
       [ 66.26465895,  58.1736831 ],
       [ 90.30720045,  81.64306345],
       [ 89.4048535 ,  87.64350868],
       [114.4503884 , 135.3976986 ],
       [134.4322939 , 159.0736094 ],
       [131.7902232 , 161.3630997 ],
       [ 99.56304732,  91.64481237],
       [132.7401928 , 166.1645443 ],
       [ 70.99088679,  54.86400482],
       [ 87.9094701 ,  78.97916469],
       [123.5807212 , 141.1303998 ],
       [107.6435614 , 119.0882793 ],
       [116.3612443 , 136.2293706 ],
       [ 62.73766606,  35.03959082],
       [112.0489047 , 130.8072421 ],
       [119.861603  , 136.2239313 ],
       [ 59.14093284,  43.34977918],
       [ 95.30589341, 106.1847674 ],
       [103.0198215 , 121.2744298 ],
       [109.2183446 , 115.1818431 ],
       [117.360594  , 137.4299149 ],
       [ 39.5196786 ,  16.02640021],
       [ 37.54642469,          nan],
       [129.9626909 , 141.0131341 ],
       [ 35.91420463,          nan],
       [ 43.85421968,  13.45049208],
       [ 72.88414185,  61.50699688],
       [120.7408594 , 133.9222973 ],
       [100.1797881 , 126.8271164 ],
       [ 59.33376537,  50.25779685],
       [120.1577567 , 144.7546765 ],
       [115.5391524 , 120.6973091 ]])

In [12]:
df.to_dict()

{'x': {0: 0.0,
  1: 25.0,
  2: 117.5832198,
  3: 108.9224662,
  4: 69.88744536,
  5: 96.83998269,
  6: 51.77594025,
  7: 35.01673734,
  8: 79.45764646,
  9: 45.3449093,
  10: 77.76713229,
  11: 55.85663802,
  12: 51.8290553,
  13: 36.07902502,
  14: 80.63255196,
  15: 124.4126644,
  16: 38.88238694,
  17: 85.24501874,
  18: 105.4849878,
  19: 36.82741469,
  20: 98.61682009,
  21: 102.1309415,
  22: 101.9740862,
  23: 122.5816416,
  24: 96.36839009,
  25: 64.89044698,
  26: 81.87156504,
  27: 83.46634106,
  28: 129.9988213,
  29: 129.5934245,
  30: 71.30088195,
  31: 89.63463319,
  32: 82.74502445,
  33: 84.29777124,
  34: 93.6549342,
  35: 37.33160529,
  36: 52.16604202,
  37: 104.833943,
  38: 106.4639932,
  39: 79.51558318,
  40: 41.4999434,
  41: 113.6214443,
  42: 90.20451127,
  43: 52.56692661,
  44: 40.50463433,
  45: 43.45292157,
  46: 122.1252001,
  47: 55.16828222,
  48: 96.44691123,
  49: 119.2731974,
  50: 52.19022426,
  51: 114.8983489,
  52: 126.0412086,
  53: 93.14307012,
  54: 131.1618641,
  55: 55.35872543,
  56: 94.59612783,
  57: 75.91878744,
  58: 96.9481879,
  59: 40.11139299,
  60: 95.54238786,
  61: 66.46740141,
  62: 120.6995729,
  63: 104.2402942,
  64: 82.65762179,
  65: 105.5341749,
  66: 87.34855969,
  67: 69.40200784,
  68: 127.3248623,
  69: 64.43689333,
  70: 66.26465895,
  71: 90.30720045,
  72: 89.4048535,
  73: 114.4503884,
  74: 134.4322939,
  75: 131.7902232,
  76: 99.56304732,
  77: 132.7401928,
  78: 70.99088679,
  79: 87.9094701,
  80: 123.5807212,
  81: 107.6435614,
  82: 116.3612443,
  83: 62.73766606,
  84: 112.0489047,
  85: 119.861603,
  86: 59.14093284,
  87: 95.30589341,
  88: 103.0198215,
  89: 109.2183446,
  90: 117.360594,
  91: 39.5196786,
  92: 37.54642469,
  93: 129.9626909,
  94: 35.91420463,
  95: 43.85421968,
  96: 72.88414185,
  97: 120.7408594,
  98: 100.1797881,
  99: 59.33376537,
  100: 120.1577567,
  101: 115.5391524},
 'y': {0: -51.0,
  1: -12.0,
  2: 134.9074137,
  3: 134.0851795,
  4: nan,
  5: 114.5306376,
  6: 31.37643731,
  7: 8.764634165,
  8: 73.28534128,
  9: 18.85986466,
  10: 72.9466086,
  11: 28.63728633,
  12: 27.18413784,
  13: 15.46895475,
  14: 77.25552457,
  15: 147.817536,
  16: 29.62914801,
  17: 92.31571653,
  18: 111.063745,
  19: 2.797485194,
  20: 98.22796195,
  21: 117.0827211,
  22: 111.1555591,
  23: 147.0235042,
  24: 99.62870641,
  25: 47.94620302,
  26: 80.51588907,
  27: 76.65159462,
  28: 155.5832066,
  29: 155.830527,
  30: 52.64410294,
  31: 100.3291952,
  32: 67.03050817,
  33: 80.8896434,
  34: 96.20409384,
  35: -6.236294705,
  36: 23.5571594,
  37: 107.7810191,
  38: 112.883657,
  39: 72.00317212,
  40: 20.25934009,
  41: 131.04384,
  42: 94.77986788,
  43: 28.21059566,
  44: 14.17040121,
  45: 23.19979105,
  46: 147.1272496,
  47: 46.89089049,
  48: 105.7562824,
  49: 126.4660848,
  50: 42.06951797,
  51: 138.6278072,
  52: 139.406306,
  53: nan,
  54: 163.3539583,
  55: 38.22375858,
  56: 105.0461097,
  57: 68.54098922,
  58: 100.2372769,
  59: 15.2017754,
  60: nan,
  61: 60.2143421,
  62: nan,
  63: 113.9349495,
  64: nan,
  65: nan,
  66: 85.16272742,
  67: 53.37775696,
  68: 160.4954569,
  69: 43.39435848,
  70: 58.1736831,
  71: 81.64306345,
  72: 87.64350868,
  73: 135.3976986,
  74: 159.0736094,
  75: 161.3630997,
  76: 91.64481237,
  77: 166.1645443,
  78: 54.86400482,
  79: 78.97916469,
  80: 141.1303998,
  81: 119.0882793,
  82: 136.2293706,
  83: 35.03959082,
  84: 130.8072421,
  85: 136.2239313,
  86: 43.34977918,
  87: 106.1847674,
  88: 121.2744298,
  89: 115.1818431,
  90: 137.4299149,
  91: 16.02640021,
  92: nan,
  93: 141.0131341,
  94: nan,
  95: 13.45049208,
  96: 61.50699688,
  97: 133.9222973,
  98: 126.8271164,
  99: 50.25779685,
  100: 144.7546765,
  101: 120.6973091}}